[Overflow-132] [FE] Implement API to profile info component in the page
framgia/sph-sun-overflow pull request #105
Opened 2023-02-17 07:06 UTC by presyos

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-132
## Commands
None
## Pre-conditions
None
## Expected Output
Should display the user details
Should display the details of other users 
## Notes

## Screenshots
![image](https://user-images.githubusercontent.com/112840596/219573300-3b5f9ac0-81de-4ee3-9d3d-1c499671fe8d.png)
![image](https://user-images.githubusercontent.com/112840596/219573341-112f1ef7-8598-46e0-be63-bd337fd5b9cc.png)

2023-02-17 07:22 UTC, nicoleamber requested changes
<img width="339" alt="image" src="https://user-images.githubusercontent.com/116238730/219576605-7ab61bc6-7476-41f1-a9fc-4a0a16e08f3c.png">

Please parse the `about_me` content. I think the React Quill editor will be used for the edit profile input.

2023-02-17 08:07 UTC, nicoleamber approved these changes

2023-02-17 09:20 UTC, jules-lucero commented on frontend/package.json
> +        "avatar-reactjs": "^1.0.5",
Remove

2023-02-17 09:21 UTC, jules-lucero approved these changes

2023-02-20 03:51 UTC, ipilikent commented
## Approved PR
- The profile stats are displayed
             - Reputation
             - Questions
             - Answers
             - Followers
             - Following
- Can count of questions by user
- Can count of answers by user 
- The watched tags are displayed
- The edit profile button is displayed
             - Hidden from another user
- The follow button is displayed
- The description of user is displayed
- The profile picture of user is displayed
- The activity and bookmark content are displayed
- The user can add tags 
             - Can remove tags
             - Can add only 5 tags
- The error and success messages are displayed

## Proof
<details>

[132 - FE Profile Component.webm](https://user-images.githubusercontent.com/110364019/220002708-5eb56d18-45c1-4442-9a32-733b580c50b1.webm)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=551244765
-----
- Total Test time: 1 hr.
- Total Comments: 0
- Total Iterations: 0

2023-02-20 05:08 UTC, merged