[Overflow-237] feature/create-tooltip
framgia/sph-sun-overflow pull request #107
Opened 2023-02-17 09:04 UTC by kenttelebanco

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-237
## Commands

## Pre-conditions

## Expected Output
Should display a tooltip when tag is selected
Should close once tag is selected again or clicked outside
## Notes
Installed React Popper (Given an element, such as a button, and a tooltip element describing it, Popper will automatically put the tooltip in the right place near the button)
```
npm i react-popper @popperjs/core
```
## Screenshots
![17 02 2023_17 03 54_REC](https://user-images.githubusercontent.com/49836629/219600656-e043a50f-2418-4cb2-9cf8-c2ecbe3866f7.png)

2023-02-17 09:23 UTC, nicoleamber requested changes
Please run the prettier commands to format your changes.

`npm run format` - for checking
`npm run format:fix` - applying needed formatting

2023-02-17 09:23 UTC, nicoleamber commented on frontend/components/molecules/Tooltip/index.tsx
> +function Tooltips() {
use arrow function expression

`const Tooltips= (): JSX.Element => {`

2023-02-17 09:23 UTC, nicoleamber commented on frontend/components/molecules/Tooltip/index.tsx
> +            </Button>
Apply proper formatting

2023-02-20 05:01 UTC, nicoleamber approved these changes

2023-02-20 07:11 UTC, presyos approved these changes

2023-02-21 08:37 UTC, ipilikent commented
## Approved PR
-  The tooltip is working
- The View Tag is displayed
- The Watch Tag button is displayed
 

## Proof
<details>

[237 - Markup Tooltip.webm](https://user-images.githubusercontent.com/110364019/220290595-e969f8c8-3787-498d-9501-47139e6e42a6.webm)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=48930172
-----
- Total Test time:  0.5 hr.
- Total Comments: 0
- Total Iterations: 0

2023-02-21 08:45 UTC, merged