[Overflow-58] feature/create-follows-api
framgia/sph-sun-overflow pull request #124
Opened 2023-02-22 06:38 UTC by kenttelebanco

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-58
## Commands
```
mutation {
  toggleFollow(user_id: ) 
}
```
## Pre-conditions

## Expected Output
Follows and Unfollows user based on its user_id
Have a condition that it wont follow if auth_user and user_id are the same
## Notes

## Screenshots
Follow User
![22 02 2023_14 36 07_REC](https://user-images.githubusercontent.com/49836629/220542369-4ec5c2f5-69a4-4eef-86ea-7d925a328a9e.png)

Unfollow User
![22 02 2023_14 36 18_REC](https://user-images.githubusercontent.com/49836629/220542407-1a164541-78bc-4642-9238-19d0a4a0bb35.png)

Auth User
![22 02 2023_14 35 53_REC](https://user-images.githubusercontent.com/49836629/220542174-b4603bf2-0870-442d-9261-d91fb59e33d6.png)

2023-02-22 07:10 UTC, nicoleamber requested changes
There's an existing model for the follow functionality: `UserRelation` so no need na to create `Follow` model

2023-02-23 06:17 UTC, nicoleamber commented
Updated the follows API to use `UserRelation` model

**Expected Output**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/116238730/220833365-8a2fc55c-4f43-45e7-83eb-08e07bddd1b2.png">

2023-02-23 06:27 UTC, jules-lucero approved these changes

2023-02-23 06:30 UTC, IanUrriza10 approved these changes

2023-02-23 06:33 UTC, IanUrriza10 approved these changes

2023-02-23 06:34 UTC, nicoleamber approved these changes

2023-02-23 06:34 UTC, merged