[Overflow-35] Create Question Form
framgia/sph-sun-overflow pull request #20
Opened 2023-01-24 03:21 UTC by IanUrriza10

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-35
## Commands
```
cd frontend
npm i 
npm run dev
```
## Pre-conditions
Install new packages

## Expected Output
A Question Form with inputs for Title, Description and Tags
Form requirements are in @/QuestionForm/schema.tsx
Not satisfying the requirements when clicking the submit button generates an alert box 
before the submit button
## Notes

## Screenshots

2023-01-24 05:38 UTC, presyos requested changes

2023-01-24 05:38 UTC, presyos commented on frontend/components/organisms/QuestionForm/index.tsx
> +import "react-quill/dist/quill.snow.css";
Please remove unused import

2023-01-24 05:38 UTC, presyos commented on frontend/components/organisms/QuestionForm/index.tsx
> +            className="border-2 border-red-400 rounded-lg text-red-400 p-2 float-right px-4 "
Please use the existing button in atoms

2023-01-24 05:44 UTC, jescabillas reviewed
Reviewed: 44mins
Comments: 2
Iteration: 1

2023-01-24 05:44 UTC, jescabillas commented on frontend/components/atoms/Editor/index.tsx
> +export default Editor;
Redundant component, please use the existing editor component from other merged PR's

2023-01-24 05:44 UTC, jescabillas commented on frontend/components/organisms/QuestionForm/index.tsx
> +          </div>
Please create components for this

2023-01-24 10:34 UTC, IanUrriza10 commented
3hrs refactor

2023-01-25 09:24 UTC, jescabillas approved these changes

2023-01-25 09:29 UTC, presyos approved these changes

2023-01-25 09:31 UTC, merged