[Overflow-450] Feature/refactor navbar
framgia/sph-sun-overflow pull request #265
Opened 2023-04-14 09:43 UTC by jescabillas

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-450

## Commands
None

## Pre-conditions
None

## Expected Output
- Follow the redesign ui in figma for navbar
- Applied animation in app logo

## Notes
None

## Screenshots
![image](https://user-images.githubusercontent.com/114911074/232730530-41621b10-505a-4304-bcdb-78df27d215e2.png)

2023-04-18 01:40 UTC, jasonchuacodes commented
![image](https://user-images.githubusercontent.com/85822633/232647441-64cde817-c0e4-47b1-ba71-f8d0fe01eefb.png)

Please double check the following values:
- [ ] shadow values - follow figma 
- [ ] align items center
- [ ] add hover state - follow figma
- [ ] double check topbar height

2023-04-18 01:50 UTC, IanUrriza10 approved these changes

2023-04-18 01:54 UTC, IanUrriza10 approved these changes, later dismissed

2023-04-18 09:54 UTC, IanUrriza10 approved these changes, later dismissed

2023-04-18 10:01 UTC, nicoleamber requested changes

2023-04-18 10:01 UTC, nicoleamber commented on frontend/components/organisms/Navbar/index.tsx
> +                        <span className="absolute -top-[19px] text-[20px] font-semibold text-primary-red transition-all duration-500 group-hover:text-white">
```suggestion
                        <span className="absolute -top-[19px] text-xl font-semibold text-primary-red transition-all duration-500 group-hover:text-white">
```

Please apply to all related.
reference: https://tailwindcss.com/docs/font-size

2023-04-19 06:15 UTC, jescabillas commented on frontend/components/organisms/Navbar/index.tsx
> +                        <span className="absolute -top-[19px] text-[20px] font-semibold text-primary-red transition-all duration-500 group-hover:text-white">
Applied

2023-04-20 06:26 UTC, kenorenzsun submitted a review, later dismissed

2023-04-20 06:35 UTC, kenorenzsun submitted a review, later dismissed

2023-04-20 07:17 UTC, kenorenzsun submitted a review, later dismissed

2023-04-20 07:17 UTC, nicoleamber approved these changes, later dismissed

2023-04-20 07:38 UTC, nicoleamber commented
## QA Feedback
* Set border width to 1px and color to Neutral/200 [#E9E2E2]

![image](https://user-images.githubusercontent.com/116238730/233297905-56bda176-b22d-4e05-910b-489ba3835bd6.png)

2023-04-20 08:33 UTC, jescabillas commented
> ## QA Feedback
> * Set border width to 1px and color to Neutral/200 [#E9E2E2]
> 
> ![image](https://user-images.githubusercontent.com/116238730/233297905-56bda176-b22d-4e05-910b-489ba3835bd6.png)

Applied changes please recheck

2023-04-20 08:54 UTC, nicoleamber commented
## Approved PR
-  All displayed the same as the Figma design
- Can hover and click on Logo to redirect me to the landing page
- Can hover and click on Notification Bell to show the notification dropdown
- Can scroll and click (redirect and mark as read) on notification items
- Can click on User Icon to show the dropdown menu for Profile and Logout
- Can click on Profile to redirect me to my Profile
- Can click on Logout to redirect me to the Login Page

## Proof
<details>

[Screencast 2023-04-20 16-47-10.webm](https://user-images.githubusercontent.com/116238730/233313465-2e2aa0c3-3d83-4c25-83eb-0d961fb53d4c.webm)

</details>

-----
- Total Test time:  0.5 hr.
- Total Comments: 1
- Total Iterations: 1

2023-04-20 08:54 UTC, nicoleamber approved these changes

2023-04-20 08:55 UTC, IanUrriza10 approved these changes

2023-04-20 08:57 UTC, kenorenzsun approved these changes

2023-04-20 08:58 UTC, merged