Feature/refactor profile page
framgia/sph-sun-overflow pull request #267
Opened 2023-04-17 05:18 UTC by IanUrriza10

## Backlog Link

## Commands

## Pre-conditions

## Expected Output

## Notes

## Screenshots

2023-04-18 09:54 UTC, nicoleamber requested changes

2023-04-18 09:54 UTC, nicoleamber commented on frontend/components/molecules/ProfileCard/index.tsx
> +                            <button
Please use the `Button` component for uniformity.

2023-04-18 09:54 UTC, nicoleamber commented on frontend/components/templates/Profile.tsx
> +// const tempTags: MITag[] = [
Remove comment

2023-04-18 09:54 UTC, nicoleamber commented on frontend/components/templates/layouts/TopLeftLayout.tsx
> +    console.log('TopLeftLayout')
```suggestion

```

2023-04-18 09:54 UTC, nicoleamber commented on frontend/components/templates/Profile.tsx
> +                <div className="bg-[#F5D3CF]  p-2 font-semibold leading-6">ACTIVITY</div>
Please set the colors in the tailwind config file and apply changes to color classes. 

* _You can copy from here for the mean time_: https://github.com/framgia/sph-sun-overflow/pull/266/files#diff-8fdab0c1827a182dfaa61b1253086037a44105350409f6701c49ebe130f6705b

2023-04-19 09:28 UTC, IanUrriza10 commented on frontend/components/molecules/ProfileCard/index.tsx
> +                            <button
Done

2023-04-19 09:28 UTC, IanUrriza10 commented on frontend/components/templates/Profile.tsx
> +// const tempTags: MITag[] = [
Done

2023-04-20 05:51 UTC, nicoleamber submitted a review, later dismissed

2023-04-20 08:22 UTC, jules-lucero submitted a review, later dismissed

2023-04-20 09:06 UTC, nicoleamber submitted a review, later dismissed

2023-04-20 09:51 UTC, jules-lucero submitted a review, later dismissed

2023-04-20 09:56 UTC, nicoleamber approved these changes, later dismissed

2023-04-20 10:46 UTC, nicoleamber commented
## QA Feedback

* Tag in Activity Questions should follow the design in Figma
* Votes should be shown as percentage with the Like icon
* Include the date in Activity cards
* Set gap space for Bookmark cards
* Bookmark icon cannot be clicked for unbookmark action

**Edit Profile**
* Limit first name and last name to less than 30 characters
* Show validation notification when there are submission errors
* Reset edit form when there are submission errors
* Upload photo not working

[Screencast 2023-04-20 18-40-51.webm](https://user-images.githubusercontent.com/116238730/233343601-29f3670f-29ea-40d4-9046-ecd5560c6ecf.webm)

2023-04-24 02:48 UTC, ipilikent commented
## Comment

1. Profile Card
- Width - 235px
2.  About Me Field
- There is validation if it exceeds 250 characters
    - Error Message "Maximum of 250 characters"
3. Follow Button
- Width - 187px
4. Like Icon
- Height - 13px Width - 13px

2023-04-24 07:10 UTC, jules-lucero submitted a review, later dismissed

2023-04-24 07:13 UTC, nicoleamber approved these changes, later dismissed

2023-04-25 06:06 UTC, jules-lucero approved these changes, later dismissed

2023-04-26 08:02 UTC, ipilikent commented
## Approved PR
- All displayed the same as the Figma design
# Profile Card
- The following and followers modals are displayed
   - Can unfollow user
   - Can follow user
   - Can see followers and following of user
- Can edit profile
   - First Name (max chars 30)
   - Last Name (max chars 30)
   - About Me (max chars 250)
   - Can upload new photo
   - Will show a preview when selecting a new photo
   - Can upload photos/GIF
   - Profile Stats is displayed
   - The position of user is displayed
   - The about me is displayed
# Activity Section
   - Can click top questions and top answers
   - Can click Tags
   - The top 5 questions is displayed
   - The top 5 answers displayed
# Bookmark Section
   - Can toggle bookmark
   - Can remove bookmark
   - Can click questions and answers in the bookmark
   - The bookmark section is infinite scrollable
- Responsive Profile Page

## Proof
<details>

![400 - Refactor Profile Page](https://user-images.githubusercontent.com/110364019/234510198-5f2c1a68-a78b-471d-8f54-5dd2c3df3d7f.gif)

</details>

Test Case:  https://docs.google.com/spreadsheets/d/1s5kbSLHk9yzEaLtnf0vnQ-5NvOUIh0mDYCXciv4q0KI/edit#gid=792229086
-----

- Total Test time: 0.75 hr.
- Total Comments: 0
- Total Iterations: 0

2023-04-26 08:03 UTC, ipilikent approved these changes

2023-04-26 08:05 UTC, jules-lucero approved these changes

2023-04-26 08:09 UTC, kenorenzsun approved these changes

2023-04-26 08:09 UTC, merged