[Overflow-355] [Overflow-449] [MARKUP] Create User Detail Page for Admin
framgia/sph-sun-overflow pull request #269
Opened 2023-04-17 09:36 UTC by jules-lucero

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-355
https://framgiaph.backlog.com/view/SUN_OVERFLOW-449

## Commands
Go to Admin User Detail Page or `http://localhost:3000/manage/users/<user-slug>`

## Pre-conditions

## Expected Output

## Notes
- Questions tab and Answers tab have the same contents
- The `ProfileCard` and `Pagination` components are not included since other devs are already working on it

## Screenshots
![image](https://user-images.githubusercontent.com/111732984/232445372-af3e7ba9-49f8-4167-b2a4-dfa41ed9f0c7.png)
![image](https://user-images.githubusercontent.com/111732984/232445397-04a39d80-7537-4b82-ad95-807f8305791d.png)
![image](https://user-images.githubusercontent.com/111732984/232445413-77b1cc73-e9f3-4b96-ac8d-fddadad81cd5.png)

2023-04-19 02:02 UTC, chevyB requested changes
Make all svgs into a component. So we can still manage to update the design if needed. Like for example, adding styling on hover.

2023-04-19 03:34 UTC, chevyB commented on frontend/components/atoms/Icons/index.tsx
> +export const Icons = {
What I think of `Old` as variable name is not in use.
You can name the new Icons as `CustomIcons` and rename back the OldIcons to `Icons`.

2023-04-19 03:54 UTC, chevyB approved these changes, later dismissed

2023-04-19 09:30 UTC, kenorenzsun approved these changes, later dismissed

2023-04-19 11:10 UTC, ipilikent commented
## Approved PR
-  All displayed the same as the Figma design
- Can click Questions, Answers, and Teams Tab
- Can grid and list questions/answers
- Display Team Cards
- Display Filters
- Can hover tabs

## Proof
<details>

![355 and 449 - Markup User Details Page (Admin)](https://user-images.githubusercontent.com/110364019/233056783-1a5a60dd-4879-4826-a402-5b9900779b11.gif)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=1295578405
-----
- Total Test time:  0.5 hr.
- Total Comments: 0
- Total Iterations: 0

2023-04-19 11:11 UTC, ipilikent approved these changes

2023-04-20 01:33 UTC, kenorenzsun approved these changes

2023-04-20 01:44 UTC, nicoleamber approved these changes

2023-04-20 01:45 UTC, merged