[Overflow-14] Implement API to Sidebars
framgia/sph-sun-overflow pull request #55
Opened 2023-02-03 08:30 UTC by IanUrriza10

## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-14
## Commands

## Pre-conditions

## Expected Output
Dynamic Watched Tag List based on user_id
Dynamic Teams List based on user_id
Working Add/Remove Watched Tags
Dynamic Teams List Based on team_id

## Notes

## Screenshots
![image](https://user-images.githubusercontent.com/114897466/216550438-570cc792-2754-4539-95e6-253b249147a2.png)
![image](https://user-images.githubusercontent.com/114897466/216550469-dbf6d346-f17c-4d06-a014-38fafdc5d64a.png)

2023-02-06 06:21 UTC, nicoleamber commented on frontend/components/templates/layouts/index.tsx
> +            />
Format properly

2023-02-06 06:37 UTC, nicoleamber commented on frontend/components/templates/layouts/index.tsx
> +                 <ToastContainer
Format properyl

2023-02-06 06:37 UTC, nicoleamber commented on frontend/components/templates/layouts/index.tsx
> +                hideProgressBar={false}
Format properly

2023-02-06 07:33 UTC, jules-lucero requested changes
Please run the Prettier script to apply proper formatting

2023-02-06 09:40 UTC, nicoleamber approved these changes

2023-02-06 10:10 UTC, jules-lucero approved these changes

2023-02-08 07:06 UTC, ipilikent commented
### Description
- The role is missing from the Member list on the Team Page

Screenshot:

![14](https://user-images.githubusercontent.com/110364019/217458265-6b1679d2-7563-45a9-92f3-c41160db5782.png)

### Expected Behavior
- The Member list must have a role on the Team Page

2023-02-08 08:44 UTC, ipilikent commented
## Proof
- User can Add tags and Remove tags
- Dynamic Watched Tag List and Dynamic Teams List is displayed
- The error and success messages are displayed

<details>

![14 - FE Sidebar Questions](https://user-images.githubusercontent.com/110364019/217475203-8f4158ed-fd43-466a-b6d5-7cc599329b33.png)

![14 - FE Sidebar Teams](https://user-images.githubusercontent.com/110364019/217475216-cd5e80f1-b0b5-4904-894e-7750dc252a30.png)

![14 - FE Sidebar Questions](https://user-images.githubusercontent.com/110364019/217479236-84a74e71-f901-44c4-b33d-8e751ef48806.gif)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=1059275291 
-----
- Total Test time: 1 hr
- Total Comments: 1
- Total Iterations: 1

2023-02-09 02:46 UTC, merged